# Generated by Django 4.2.7 on 2025-10-27 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_rejected', 'Task Rejected'), ('task_accepted', 'Task Accepted'), ('approaching_deadline', 'Approaching Deadline'), ('quality_issue', 'Quality Issue Alert'), ('efficiency_alert', 'Efficiency Alert'), ('report_submitted', 'Report Submitted')], max_length=100),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('technician', 'Technician Report'), ('quality', 'Quality Inspector Report')], db_index=True, max_length=50)),
                ('content', models.TextField(help_text='Detailed notes, findings, and observations from the operation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.joborder')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.task')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
