# Generated by Django 4.2.7 on 2025-10-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_joborder_description_notification_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actual_time_seconds',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
        migrations.AddField(
            model_name='report',
            name='actual_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='report',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
