# Generated by Django 4.2.7 on 2025-10-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_task_actual_time_seconds_remove_task_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='report',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_time',
        ),
    ]
