# Generated by Django 4.2.7 on 2025-10-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_report_end_time_remove_report_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='report',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
