# Generated by Django 4.2.7 on 2025-10-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_actual_time_seconds_task_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actual_time_seconds',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
    ]
