# Generated by Django 5.2.7 on 2025-10-27 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_task_actual_time_seconds_remove_task_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.device'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Task_Device_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='core.device')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='core.task')),
            ],
            options={
                'verbose_name': 'Task Device Assignment',
                'verbose_name_plural': 'Task Device Assignments',
                'db_table': 'task_device_assignments',
                'unique_together': {('task', 'device')},
            },
        ),
    ]
