# Generated by Django 5.2.7 on 2025-10-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_task_actual_time_seconds_task_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_progress', 'In Progress'), ('pending-approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('done', 'Done')], db_index=True, default='available', max_length=50),
        ),
    ]
