# Generated by Django 5.2.7 on 2025-10-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('technician', 'Technician Task'), ('quality', 'Quality Inspection Task'), ('tester', 'Tester Task')], db_index=True, default='technician', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('technician', 'Technician'), ('quality_inspector', 'Quality Inspector'), ('supervisor', 'Supervisor'), ('planning', 'Planning Engineer'), ('admin', 'System Admin'), ('tester', 'Tester')], db_index=True, default='technician', max_length=50),
        ),
    ]
