# Generated by Django 5.2.7 on 2025-10-29 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_task_task_type_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='joborder',
            name='job',
            field=models.ForeignKey(blank=True, help_text='The predefined job template for this order.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_orders', to='core.job'),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=200)),
                ('standard_time_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('task_type', models.CharField(choices=[('technician', 'Technician Task'), ('quality', 'Quality Inspection Task'), ('tester', 'Tester Task')], default='technician', max_length=50)),
                ('order', models.PositiveIntegerField(help_text="The order of this process in the job's workflow.")),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='core.job')),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
                'db_table': 'processes',
                'ordering': ['job', 'order'],
                'unique_together': {('job', 'order')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='process',
            field=models.ForeignKey(blank=True, help_text='The process template for this task.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.process'),
        ),
    ]
