# Generated by Django 5.2.7 on 2025-10-30 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_pending_status_to_inspection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("task_rejected", "Task Rejected"),
                    ("task_accepted", "Task Accepted"),
                    ("approaching_deadline", "Approaching Deadline"),
                    ("quality_issue", "Quality Issue Alert"),
                    ("efficiency_alert", "Efficiency Alert"),
                    ("report_submitted", "Report Submitted"),
                    ("task_ready_for_inspection", "Task Ready for Inspection"),
                    ("task_ready_for_testing", "Task Ready for Testing"),
                    ("task_completed", "Task Completed"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                    ("pending_qa", "Pending QA"),
                    ("qa_approved", "QA Approved"),
                    ("pending_supervisor", "Pending Supervisor"),
                    ("supervisor_approved", "Supervisor Approved"),
                    ("pending_tester", "Pending Tester"),
                    ("tester_approved", "Tester Approved"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="available",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("technician", "Technician"),
                    ("quality", "Quality Inspector"),
                    ("supervisor", "Supervisor"),
                    ("planning", "Planning Engineer"),
                    ("admin", "System Admin"),
                    ("tester", "Tester"),
                ],
                db_index=True,
                default="technician",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="TesterReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tester_reviews",
                        to="core.task",
                    ),
                ),
                (
                    "tester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tester_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tester Review",
                "verbose_name_plural": "Tester Reviews",
                "db_table": "tester_reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
