# Generated by Django 5.2.7 on 2025-10-30 00:54

from django.db import migrations


def migrate_statuses_forward(apps, schema_editor):
    """
    Migrate old status values to new ones:
    - 'pending-approval' → 'pending_qa' (tasks waiting for QA)
    - 'approved' → 'qa_approved' (tasks approved by QA)
    - 'done' → 'pending_qa' (completed by technician, awaiting QA)
    """
    Task = apps.get_model('core', 'Task')
    
    # Migrate pending-approval tasks to pending_qa
    Task.objects.filter(status='pending-approval').update(status='pending_qa')
    
    # Migrate approved tasks to qa_approved (they passed QA)
    Task.objects.filter(status='approved').update(status='qa_approved')
    
    # Migrate done tasks to pending_qa (ready for QA inspection)
    Task.objects.filter(status='done').update(status='pending_qa')


def migrate_statuses_backward(apps, schema_editor):
    """
    Revert migrations (rarely used, but good for safety)
    """
    Task = apps.get_model('core', 'Task')
    
    # Revert back to old statuses
    Task.objects.filter(status='pending_qa').update(status='pending-approval')
    Task.objects.filter(status='qa_approved').update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_notification_type_alter_task_status_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_statuses_forward, migrate_statuses_backward),
    ]
