# Generated by Django 5.2.7 on 2025-10-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_migrate_task_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_progress', 'In Progress'), ('done', 'Done'), ('pending_qa', 'Pending QA'), ('qa_approved', 'QA Approved'), ('pending_tester', 'Pending Tester'), ('tester_approved', 'Tester Approved'), ('pending_supervisor', 'Pending Supervisor'), ('supervisor_approved', 'Supervisor Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='available', max_length=50),
        ),
    ]
